name: clean_architecture_movie
description: Example architecture clean.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dartz:
  get_it:
  injectable:
  bloc:
  http:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator:
  build_runner:

flutter:
  uses-material-design: true
