name: clean_architecture_triple
description: Example architecture clean triple.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  intl: ^0.17.0-nullsafety.2
  dartz: ^0.10.0-nullsafety.1
  flutter_triple: ^0.0.26
  equatable: ^2.0.0-nullsafety.4
  get_it: ^6.0.0-nullsafety.2
  http: ^0.13.0-nullsafety.0
  flutter_svg: ^0.21.0-nullsafety.0
  animations: ^2.0.0-nullsafety.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/animated/
    - assets/icons/
