name: clean_architecture_bloc
description: Example architecture clean.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  intl:
  flutter_bloc:
  dartz:
  get_it:
  http:
  flare_flutter:
  equatable:
  scroll_snap_list:
  flutter_svg:
  animations:
  data_connection_checker:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/animated/
    - assets/icons/
